services:
  - type: web
    name: swipebox-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
      - package.json
      - package-lock.json
      - index.js
      - public/**
